-- Настройки, которые можно менять в окне Properties для каждого объекта отдельно
go.property("speed", 350)
go.property("lifetime", 5.0)

function init(self)

	-- Поворот и скорость
	local rot = go.get_rotation()
	local forward = vmath.rotate(rot, vmath.vector3(1, 0, 0))
	forward = vmath.normalize(forward)
	--local speed = 350
	local vel = forward * self.speed
	go.set("#collisionobject", "linear_velocity", vel)

	-- Удаление через 5 секунд
	timer.delay(self.lifetime, false, function()
		go.delete()
	end)
end
