function init(self)
	self.health = 3 -- здоровье врага
	self.isRight = false -- переменная определяющая сторону
	self.walk_speed = 30
	self.mode = 0 -- режим поведения (0 - прогулка, 1 - погоня с атакой, -1 - ничего - падение)

	-- Запоминаем самый первый X при старте игры, чтобы было с чем сравнивать (для прыжка - враг прыгает, если предыдущая координата по x не изменилась)
	self.last_x = go.get_position().x

	-- Сохраняем ID игрока в переменную (хеш-строка)
	self.player_id = hash("/player_prefab/player")
	self.vision_distance = 230
end

function update(self, dt)
	check_player_distance(self) -- чекаем расстояние до игрока
	
	if self.mode == 0 then
		walk(self) -- функция прогулки врага

		jump(self)
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		-- сравниваем ГРУППУ столкновения, а не динамический ID объекта
		if message.other_group == hash("knife") then 
			print("Враг потерял здоровье")
			self.health = self.health - 1

			--создаем толчок
			-- Вычисляем направление (1 вправо, -1 влево) на основе взаимного расположения
			local dir_x = (go.get_position().x - message.other_position.x) > 0 and 1 or -1

			-- Задаем скорость по оси X (700 — сила толчка)
			go.set("#enem", "linear_velocity", vmath.vector3(dir_x * 700, 0, 0))
			
			--вызываем анимацию получения урона
			take_damage_anim(self)
		end
	end

	-- Проверяем, что произошло столкновение типа "триггер"
	if message_id == hash("trigger_response") then

		-- Проверяем, что враг коснулся именно группы patrol_wall (нашей таблички)
		if message.group == hash("patrol_wall") then

			-- message.enter равен true в самый первый кадр касания
			if message.enter then
				-- Разворачиваем врага!
				rotate_opposite_side(self)
			end
		end
	end
end

-- Задать спрайт врагу в зависимости от здоровья
function set_sprite_of_damage(self)
	if self.health == 3 then
		sprite.play_flipbook("sprite_holder#enemy_sprite", "Enemy")
	elseif self.health == 2 then
		sprite.play_flipbook("sprite_holder#enemy_sprite", "DamegedEnem1")
	elseif self.health == 1 then
		sprite.play_flipbook("sprite_holder#enemy_sprite", "DamegedEnem2")
	elseif self.health <= 0 then
		sprite.play_flipbook("sprite_holder#enemy_sprite", "DamegedEnem3")
	end
end

-- Функция получения урона
function take_damage_anim(self)
	self.mode = -1

	-- задаем скин повреждения в сооответствии со здоровьем
	set_sprite_of_damage(self);

	--if self.health > 0 then
		timer.delay(2, false, function()
			-- Этот код выполнится ровно через 2 секунды

			-- Восстанавливаем режим только если враг всё ещё жив (если в течение таймера)
			if self.health > 0 then
				go.set_rotation(vmath.quat(0, 0, 0, 1)) --обнуляем поворот после попадания (на случай если враг упал после удара)
				self.mode = 0; -- после подьема задаем поведенческий режим на ходьбу
			else
				self.mode = -1;

				msg.post("sprite_holder#glitch_effect", "disable_glitch")
				
				-- 3 — это время в секундах, через которое коллайдер уберется
				timer.delay(3, false, function()
					msg.post("#enem", "disable")
				end)

				
				msg.post("#enemy_controller", "disable")
			end
		end)
	--else
	--end
end

-- отзеркаливание врага в противоположную сторону
function rotate_opposite_side(self)
	if self.isRight == true then -- если сторона правая
		self.isRight = false
		sprite.set_hflip("sprite_holder#enemy_sprite", false) -- зеркаалим врага влево
		sprite.set_hflip("pistol#pistol_sprite", false) -- зеркаалим пистолет врага влево
	else
		self.isRight = true
		sprite.set_hflip("sprite_holder#enemy_sprite", true) -- зеркаалим врага вправо
		sprite.set_hflip("pistol#pistol_sprite", true) -- зеркаалим пистолет врага вправо
	end
end

-- Функция хотьбы врага
function walk(self)
	go.set_rotation(vmath.quat(0, 0, 0, 1)) --обнуляем поворот
	
	local v = go.get("#enem", "linear_velocity") -- берем компонент движения коллайдера

	-- Двигаем или останавливаем куб в зависимости от сохраненного направления
	v.x = 0
	
	if self.isRight == true then -- если сторона правая
		v.x = 1 * self.walk_speed
	else
		v.x = -1 * self.walk_speed
	end

	go.set("#enem", "linear_velocity", v)
end

-- Функция прыжка врага
function jump(self)
	local pos = go.get_position()

	-- ЧИТАЕМ СКОРОСТЬ прямо из физического тела, чтобы узнать движется ли враг
	local v = go.get("#enem", "linear_velocity") 

	-- Если скорость по X задана (враг должен идти) И координата X не сдвинулась
	if v.x ~= 0 and math.abs(pos.x - self.last_x) < 0.01 then -- если задаваемая скорость нелу не 0 и расстояние с предыдущей точки и текущей по x не изменилась - прыгаем
		v.y = 350 -- Задаем скорость прыжка вверх

		timer.delay(1, false, function()
			
			-- возвращаем скин повреждения в сооответствии со здоровьем
			set_sprite_of_damage(self);
			
		end)

		if self.health > 0 then
			-- Анимация прыжка
			sprite.play_flipbook("sprite_holder#enemy_sprite", "EnemyJump")
		end
		go.set("#enem", "linear_velocity", v) -- Применяем её к физическому телу
	end

	-- В самом конце записываем текущий X для следующего кадра
	self.last_x = pos.x
end

function check_player_distance(self)
	if self.mode ~= -1 then -- если по поведению враг не ранен и не убит (-1 = ранен или убит) - высчитываем расстояние до игрока
		-- Берем позицию текущего объекта (Врага)
		local enemy_pos = go.get_position()

		-- Берем позицию Игрока, передав его сохраненный ID
		local player_pos = go.get_position(self.player_id)

		-- Вычисляем расстояние между ними (длину вектора разности)
		local distance = vmath.length(enemy_pos - player_pos)

		-- Теперь проверяем дистанцию (например, меньше 150 пикселей)
		if distance < self.vision_distance then
			print("Игрок подошел близко! Расстояние: " .. distance)
			-- Здесь будет логика атаки
			attack_behaviour(self)
			
			self.mode = 1
		else
			self.mode = 0
		end
	end
end

function attack_behaviour(self)
	local enemy_pos = go.get_position()
	local target_pos = go.get_position(self.player_id)
	
	local dx = target_pos.x - enemy_pos.x
	local dy = target_pos.y - enemy_pos.y
	local angle = math.atan2(dy, dx)

	local angle = math.atan2(dy, dx)

	if dx < 0 then	
		angle = angle - math.pi
		sprite.set_hflip("pistol#pistol_sprite", false)
		sprite.set_hflip("sprite_holder#enemy_sprite", false)
	else
		sprite.set_hflip("pistol#pistol_sprite", true)
		sprite.set_hflip("sprite_holder#enemy_sprite", true)
	end
	
	go.set_rotation(vmath.quat_rotation_z(angle), "pistol")
end

--function attack_behaviour(self)
	-- Берём позицию врага (или самого пистолета, если он смещён)
	--local enemy_pos = go.get_position()
	--local target_pos = go.get_position(self.player_id)

	--local dx = target_pos.x - enemy_pos.x
	--local dy = target_pos.y - enemy_pos.y
	--local angle = math.atan2(dy, dx)   -- угол в радианах

	-- Поворачиваем спрайт пистолета (компонент внутри дочернего объекта)
	--sprite.set_rotation("pistol", angle)
--end